shop_market/shop_market/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from shop_market.settings import MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^xf/', include('xfmart.urls', namespace='xf')),
    url(r'^user/', include('user.urls', namespace='user')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

shop_market/user/urls.py
from django.conf.urls import url

from user import views


urlpatterns = [
    # 注册
    url(r'^register/', views.register, name='register'),
    # 检查用户名是否存在
    url(r'^checkuser', views.check_user, name='checkuser'),
    # 登录
    url(r'^login/', views.login, name='login'),
    # 登出
    url(r'^logout/', views.logout, name='logout'),
]

shop_market/xfmart/urls.py
from django.conf.urls import url

from xfmart import views

urlpatterns = [
    # 首页
    url(r'^home/', views.index, name='home'),
    # 闪购页面
    url(r'^market/$', views.market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)/', views.user_market, name='market_param'),
    # 购物车
    url(r'^cart/', views.cart, name='cart'),
    # 我的页面
    url(r'^mine/', views.mine, name='mine'),

    # 添加购物车商品
    url(r'^addCart/', views.add_cart, name='addCart'),
    # 删除购物车商品
    url(r'^subCart/', views.sub_cart, name='subCart'),
    # 改变购物车商品状态
    url(r'^changeCartStatus/', views.change_cart_status, name='changeCartStatus'),
    # 下单
    url(r'^generateOrder/', views.generate_order, name='generateOrder'),
    # 修改订单状态（支付）
    url(r'^changeOrderStatus/', views.change_order_status, name='changeOrderStatus'),
    # 待支付页面
    url(r'^waitPay/', views.wait_pay, name='waitPay'),
    # 待收货页面
    url(r'^orderPayed/', views.order_payed, name='orderPayed'),
    # 待支付跳转到支付页面
    url(r'^waitPaytoPay', views.wait_pay_to_pay, name='waitPaytoPay')
]

shop_market/xfmart/models.py
from django.db import models

from user.models import UserModel


class Main(models.Model):
    img = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    trackid = models.CharField(max_length=16)

    class Meta:
        abstract = True


class MainWheel(Main):
    """首页banner"""
    class Meta:
        db_table = 'xf_wheel'


class MainNav(Main):
    """首页导航栏"""
    class Meta:
        db_table = 'xf_nav'


class MainMustbuy(Main):
    """必购"""
    class Meta:
        db_table = 'xf_mustbuy'


class MainShop(Main):
    """首页商店"""
    class Meta:
        db_table = 'xf_shop'


class MainShow(Main):
    """首页商品展示"""
    categoryid = models.CharField(max_length=16)
    brandname = models.CharField(max_length=100)   # 分类名称

    img1 = models.CharField(max_length=200)   # 图片
    childcid1 = models.CharField(max_length=16)   # 子类id
    productid1 = models.CharField(max_length=16)
    longname1 = models.CharField(max_length=100)   # 商品名称
    price1 = models.FloatField(default=0)   # 折后价
    marketprice1 = models.FloatField(default=1)   # 原价

    img2 = models.CharField(max_length=200)  # 图片
    childcid2 = models.CharField(max_length=16)
    productid2 = models.CharField(max_length=16)
    longname2 = models.CharField(max_length=100)  # 商品名称
    price2 = models.FloatField(default=0)  # 折后价
    marketprice2 = models.FloatField(default=1)  # 原价

    img3 = models.CharField(max_length=200)  # 图片
    childcid3 = models.CharField(max_length=16)
    productid3 = models.CharField(max_length=16)
    longname3 = models.CharField(max_length=100)  # 商品名称
    price3 = models.FloatField(default=0)  # 折后价
    marketprice3 = models.FloatField(default=1)  # 原价

    class Meta:
        db_table = 'xf_mainshow'


# 闪购页面-左侧类型表
class FoodType(models.Model):
    """商品类型表"""
    typeid = models.CharField(max_length=16)   # 分类id
    typename = models.CharField(max_length=100)   # 商品分类名称
    childtypenames = models.CharField(max_length=200)   # 商品
    typesort = models.IntegerField(default=1)   # 排序

    class Meta:
        db_table = 'xf_foodtypes'


class Goods(models.Model):
    """商品表"""
    productid = models.CharField(max_length=16)  # 商品id
    productimg = models.CharField(max_length=200)   # 商品图片
    productname = models.CharField(max_length=100)   # 商品名称
    productlongname = models.CharField(max_length=200)  # 商品长名称
    isxf = models.IntegerField(default=1)
    pmdesc = models.CharField(max_length=100)
    specifics = models.CharField(max_length=100)   # 规格
    price = models.FloatField(default=0)   # 折后价
    marketprice = models.FloatField(default=1)   # 原价
    categoryid = models.CharField(max_length=16)  # 分类id
    childcid = models.CharField(max_length=16)   # 子分类id
    childcidname = models.CharField(max_length=100)  # 名称
    dealerid = models.CharField(max_length=16)
    storenums = models.IntegerField(default=1)  # 库存
    productnum = models.IntegerField(default=1)   # 销量排序

    class Meta:
        db_table = 'xf_goods'


class CartModel(models.Model):
    """购物车表"""
    user = models.ForeignKey(UserModel)  # 关联用户
    goods = models.ForeignKey(Goods)   # 关联商品
    c_num = models.IntegerField(default=1)    # 商品数量
    is_select = models.BooleanField(default=True)   # 是否选中

    class Meta:
        db_table = 'xf_cart'


class OrderModel(models.Model):
    """订单表"""
    user = models.ForeignKey(UserModel)   # 关联用户
    o_num = models.CharField(max_length=64)  # 订单编号
    # 0 表示已下单，但未付款， 1 已付款未发货， 2 已付款已发货
    o_status = models.IntegerField(default=0)   # 状态
    o_create = models.DateTimeField(auto_now_add=True)  # 创建时间

    class Meta:
        db_table = 'xf_order'


class OrderGoodsModel(models.Model):
    """商品订单关联表"""
    goods = models.ForeignKey(Goods)   # 关联商品
    order = models.ForeignKey(OrderModel)   # 关联的订单
    goods_num = models.IntegerField(default=1)   # 商品数量

    class Meta:
        db_table = 'xf_order_goods'

shop_market/templates/order/order_info.html
{% extends 'base.html' %}
{% load static %}

{% block EXTJS %}
    <script type="text/javascript" src="{% static 'app/order/js/order.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="order_info" class="container">

    <!--订单编号-->
    <h3>订单编号:{{ order.o_num }}</h3>
    {% csrf_token %}
    <!--处理结束-->
    <ul>

        <!--所有订单信息展示-->
        {% for goods in order.ordergoodsmodel_set.all %}
            <li>
                <!--商品名称展示-->
                <img src="{{ goods.goods.productimg }}">
                <p>{{ goods.goods.productname }}</p>
                <span> <!-- 数量展示 -->{{ goods.goods_num }}</span>
            </li>
        {% endfor %}
        <!--订单处理结束-->

    </ul>
        <!--订单id展示-->
        <button id="alipay" class="btn btn-success btn-block" orderid="{{ order.id }}">Alipay</button>

    </div>


{% endblock %}

shop_market/templates/order/order_list_payed.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待收货订单列表</h3>

    <ul>
        <!--订单展示-->
        {% for order in orders %}
            <li>
                <a href="#">
                    <p><!-- 订单id -->订单编号：{{ order.o_num }}</p>
                    <p><!-- 数量 --></p>
                    {% for goods in order.ordergoodsmodel_set.all %}
                        <!--展示商品的名称-->
                        <li>
                            <img src="{{ goods.goods.productimg }}" alt="">
                        <span>{{ goods.goods.productlongname }}</span>
                         <span> <!-- 数量展示 -->数量：{{ goods.goods_num }}</span>
                        </li>
                        {% endfor %}
                        <!--处理结束-->
                </a>
            </li>
        {% endfor %}
        <!--订单处理结束-->

    </ul>


{% endblock %}

shop_market/templates/order/order_list_wait_pay.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <h3>待付款订单列表</h3>

    <ul>
        <!--订单信息展示-->
        {% for order in orders %}
            <li>
                <a href="{% url 'xf:waitPaytoPay' %}?order_id={{ order.id }}">
                    <p><!-- 订单id --></p>
                    <p><!-- 数量 -->订单编号：{{ order.o_num }}</p>
                        <!--展示商品的名称-->
                        {% for goods in order.ordergoodsmodel_set.all %}
                        <li>
                            <img src="{{ goods.goods.productimg }}" alt="">
                            <span>{{ goods.goods.productlongname }}</span>
                            <p><span>数量：{{ goods.goods_num }}</span></p>
                        </li>
                            {% endfor %}
                        <!--处理结束-->
                </a>
            </li>
        {% endfor %}
        <!--订单处理结束-->


    </ul>


{% endblock %}