stu_ms/stu/urls.py
from django.conf.urls import url
from stu import views


from rest_framework.routers import SimpleRouter

router = SimpleRouter()
# 注册rest路由
router.register(r'^api/student', views.ApiStudent)
router.register(r'^api/grade', views.ApiGrade)

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^head/', views.head, name='head'),
    url(r'^left/', views.left, name='left'),
    url(r'^main/', views.main, name='main'),
    url(r'^grade/', views.grade, name='grade'),
    url(r'^addgrade/', views.add_grade, name='addgrade'),
    url(r'^student/', views.student, name='student'),
    url(r'^addstu/', views.add_stu, name='addstu'),
    url(r'^editgrade/', views.add_grade, name='editgrade'),
    url(r'^delgrade/', views.del_grade, name='delgrade'),
    url(r'^editstu/', views.add_stu, name='editstu'),
    url(r'^delstu/', views.del_stu, name='delstu'),

]

# 使定义的rest风格的url生效
urlpatterns += router.urls

# handler404 = views.badpage404

stu_ms/stu_ms/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from stu_ms.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^stu/', include('stu.urls', namespace='stu')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^mytest/', include('mytest.urls', namespace='mytest'))
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

stu_ms/user/urls.py
from django.conf.urls import url
from user import views


urlpatterns = [
    # django自带的登录注册
    url(r'^djregister/', views.djregister, name='djregister'),
    url(r'^djlogin/', views.djlogin, name='djlogin'),
    url(r'^djlogout', views.djlogout, name='djlogout'),

    # 自己实现的注册
    url(r'^register', views.register, name='register'),
    url(r'^login', views.login, name='login'),
    url(r'^logout', views.logout, name='logout'),

    # 权限/角色
    url(r'^userper', views.userper, name='userper'),
]

stu_ms/templates/addgrade.html
{% extends 'base.html' %}
{% block title %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="generator" content=""/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
{% endblock %}
{% block extCSS %}
    <link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print"/>
    <link href="/static/css/print.css" rel="stylesheet" type="text/css" media="print"/>
{% endblock %}
{% block extJS %}
    <script src="/static/js/jquery-1.10.1.min.js"></script>
    <script src="/static/js/side.js" type="text/javascript"></script>
    <!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
    <script type="text/javascript">
        $(function () {
            var path = location.href;
            var id = path.split('=')[1];
            if(id){
                $.get('/stu/api/grade/' + id, function (msg) {
                $('[name="grade_name"]').val(msg.g_name)
            });
            }else {
                $('[name="submit"]').attr('onclick', 'addgrade()')
            }

        });
        function addgrade() {
            var csrf = $('[name="csrfmiddlewaretoken"]').val();
            $.ajax({
                url: '/stu/api/grade/',
                type: 'POST',
                dataType:'json',
                headers: {'X-CSRFToken': csrf},
                data: {'g_name': $('input[name="grade_name"]').val()},
                success: function () {
                    alert('增加成功');
                    location.href = '/stu/grade/'
                },
                error: function () {
                    alert('增加失败')
                }
            })
        }
        function editgrade() {
            var path = location.href;
            grade_id = path.split('=')[1];
            var csrf = $('[name="csrfmiddlewaretoken"]').val();
            $.ajax({
                url: '/stu/api/grade/' + grade_id + '/',
                type: 'PATCH',
                dataType: 'json',
                headers: {'X-CSRFToken': csrf},
                data: {'g_name': $('input[name="grade_name"]').val()},
                success: function () {
                    alert('修改成功');
                    location.href = '/stu/grade/'
                },
                error: function () {
                    alert('修改失败')
                }
            })
        }
    </script>
{% endblock %}

{% block content %}
    <!-- Popup -->
    <div id="Popup">

        <!-- SubPopup -->
        <div id="SubPopup">
            <script type="text/javascript">
                $(function () {
                    $(".select").each(function () {
                        var s = $(this);
                        var z = parseInt(s.css("z-index"));
                        var dt = $(this).children("dt");
                        var dd = $(this).children("dd");
                        var _show = function () {
                            dd.slideDown(200);
                            dt.addClass("cur");
                            s.css("z-index", z + 1);
                        };
                        var _hide = function () {
                            dd.slideUp(200);
                            dt.removeClass("cur");
                            s.css("z-index", z);
                        };
                        dt.click(function () {
                            dd.is(":hidden") ? _show() : _hide();
                        });
                        dd.find("a").click(function () {
                            dt.html($(this).html());
                            _hide();
                        });
                        $("body").click(function (i) {
                            !$(i.target).parents(".select").first().is(s) ? _hide() : "";
                        });
                    })
                })
            </script>
            {% if grade.id %}
                <form action="{% url 'stu:addgrade' %}?id={{ grade.id }}" method="post">
            {% else %}
                <form action="{% url 'stu:addgrade' %}?id=0" method="post">
            {% endif %}

            {% csrf_token %}
            <div class="form_boxC">
                <table cellpadding="0" cellspacing="0">
                    <tr>
                        <th width="100">班级名称</th>
                        <td>
                            <div class="selectbox" style="width:230px;">
                                <input type="text" name="grade_name" placeholder="请填入班级名称" value="{{ grade.g_name }}">
                            </div>
                        </td>
                    </tr>

                </table>
                <div id="BtmBtn">
                    <div class="btn_box floatR">
                        <input name="submit" type="submit" onclick="editgrade();" value="提交">
                    </div>
                </div>
            </div>
            </form>
        </div>
        <!-- SubPopup -->


    </div>
    <!-- /Popup -->
{% endblock %}

stu_ms/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    {% block extCSS %}

    {% endblock %}
    {% block extJS %}

    {% endblock %}
</head>
{% block indexbody %}

{% endblock %}
<body>
    {% block content %}
    
    {% endblock %}
    {% block footer %}
    
    {% endblock %}
</body>
</html>

stu_ms/templates/grade.html
{% extends 'base.html' %}
{% block title %}
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="generator" content=""/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
{% endblock %}
{% block extCSS %}
<link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print"/>
<link href="/static/css/print.css" rel="stylesheet" type="text/css" media="print"/>
{% endblock %}
    {% block extJS %}
    <script src="/static/js/jquery-1.10.1.min.js"></script>
    <script src="/static/js/side.js" type="text/javascript"></script>
            <!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
        <script type="text/javascript">
        function delgrade(i) {
            csrf = $('[name="csrfmiddlewaretoken"]').val();
            $.ajax({
                url:'/stu/api/grade/' + i + '/',
                type:'DELETE',
                dataType: 'json',
                headers: {'X-CSRFToken':csrf},
                success:function (data) {
                    alert('删除成功');
                    location.href = '/stu/grade/'
                },
                error:function (data) {
                    alert('删除失败')
                }
            });
        }
        $(function () {
            $.get('/stu/api/grade/', function (msg) {
                var tr_html = '';
                var msg = msg['data']['results'];
                for (var i=0; i < msg.length; i++){
                    tr_html += '<tr>';
                    tr_html += '<td>' + msg[i]['id'] + '</td>';
                    tr_html += '<td>' + msg[i].g_name + '</td>';
                    tr_html += '<td>' + msg[i].g_create_time + '</td>';
                    tr_html += '<td><a href="{% url 'stu:editgrade' %}?id=' + msg[i]['id'] + '">编辑</a> |';
                    tr_html += '<a href="javascrip:void(0)" onclick="delgrade(' + msg[i]['id'] + ');">删除</a></td>';
                    tr_html += '</tr>';
                }
                $('#grade').append(tr_html);
            })
        })
        </script>
    {% endblock %}
{% block content %}
<!-- MainForm -->
<div id="MainForm">
    <div class="form_boxA">
        <h2>班级信息列表</h2>
        <table cellpadding="0" cellspacing="0" id="grade">
            <tr>
                <th>序号</th>
                <th>班级名称</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
{#            {% for grade in pages %}#}
{#                <tr>#}
{#                    <td>{{ grade.id }}</td>#}
{#                    <td>{{ grade.g_name }}</td>#}
{#                    <td>{{ grade.g_create_time }}</td>#}
{#                    <td><a href="{% url 'stu:editgrade' %}?id={{ grade.id }}">编辑</a> | <a#}
{#                            href="{% url 'stu:delgrade' %}?id={{ grade.id }}">删除</a></td>#}
{#                </tr>#}
{#            {% endfor %}#}

        </table>
        <p class="msg">共找到47条年度预算记录，当前显示从第1条至第10条</p>
    </div>

    <ul id="PageNum">
        <li><a href="{% url 'stu:grade' %}">首页</a></li>
        {% if pages.has_previous %}
            <li><a href="{% url 'stu:grade' %}?page_num={{ pages.previous_page_number }}">上一页</a></li>
        {% endif %}
        {% for i in pages.paginator.page_range %}
            {% ifequal pages.number i %}
                <li><a href="{% url 'stu:grade' %}?page_num={{ i }}" class="active">{{ i }}</a></li>
            {% else %}
                <li><a href="{% url 'stu:grade' %}?page_num={{ i }}">{{ i }}</a></li>
            {% endifequal %}
        {% endfor %}
        {% if pages.has_next %}
            <li><a href="{% url 'stu:grade' %}?page_num={{ pages.next_page_number }}">下一页</a></li>
        {% endif %}
        <li><a href="{% url 'stu:grade' %}?page_num={{ pages.paginator.num_pages }}">尾页</a></li>
    </ul>
</div>
{% endblock %}

stu_ms/templates/head.html
{#{% load static %}#}
{% extends 'base.html' %}
{% block title %}
    头部
{% endblock %}
{% block extCSS %}
<link rel="stylesheet" type="text/css" href="/static/css/public.css" />
{% endblock %}
{% block extJS %}
<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/public.js"></script>
{% endblock %}

{% block content %}
<!-- 头部 -->
	<div class="head">
		<div class="headL">
			<img class="headLogo" src="/static/img/logLOGO.png"/>
		</div>
		<div class="headR">
			<span style="color:#FFF">欢迎： </span> <a href="{% url 'user:logout' %}" rel="external">【退出】</a>
		</div>
	</div>
{% endblock %}

stu_ms/templates/index.html
{% extends 'base.html' %}

{% block title %}
    首页
{% endblock %}
{% block indexbody %}
    <frameset rows="100,*" cols="*" scrolling="No" framespacing="0"
              frameborder="no" border="0">
        <frame src="{% url 'stu:head' %}"
               name="headmenu" id="mainFrame" title="mainFrame"><!-- 引用头部 -->
        <!-- 引用左边和主体部分 -->
        <frameset rows="100*" cols="220,*" scrolling="No"
                  framespacing="0" frameborder="no" border="0">
            <frame
                    src="{% url 'stu:left' %}" name="leftmenu" id="mainFrame" title="mainFrame">
            <frame src="{% url 'stu:grade' %}" name="main" scrolling="yes" noresize="noresize"
                   id="rightFrame" title="rightFrame">
        </frameset>
    </frameset>
{% endblock %}

stu_ms/templates/left.html
{% extends 'base.html' %}
{% block title %}
    首页左侧导航
{% endblock %}
{% block extCSS %}
    <link rel="stylesheet" type="text/css" href="/static/css/public.css"/>
{% endblock %}
{% block extJS %}
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
    <script type="text/javascript" src="/static/js/public.js"></script>
{% endblock %}

{% block content %}
    <div class="container">
        <!-- 左边节点 -->
        <div class="leftsidebar_box">
            <a href="{% url 'stu:main' %}" target="main">
                <div class="line">
                    <img src="/static/img/coin01.png"/>&nbsp;&nbsp;首页
                </div>
            </a>
                <dl class="system_log">
                {% for permission in user.role.r_p.all %}
                    {% ifequal permission.p_en 'GRADELIST' %}
                        <dt>
                            <img class="icon1" src="/static/img/coin03.png"/><img class="icon2"
                                                                                  src="/static/img/coin04.png"/>
                            班级管理<img class="icon3"
                                     src="/static/img/coin19.png"/><img class="icon4"
                                                                        src="/static/img/coin20.png"/>
                        </dt>
                        <dd>
                            <img class="coin11" src="/static/img/coin111.png"/><img class="coin22"
                                                                                    src="/static/img/coin222.png"/><a
                                class="cks" href="{% url 'stu:grade' %}"
                                target="main">班级列表</a><img class="icon5" src="/static/img/coin21.png"/>
                        </dd>
                    {% endifequal %}
                {% endfor %}
                {% for permission in user.role.r_p.all %}
                    {% ifequal permission.p_en 'GRADEADD' %}
                        <dd>
                            <img class="coin11" src="/static/img/coin111.png"/><img class="coin22"
                                                                                    src="/static/img/coin222.png"/><a
                                class="cks" href="{% url 'stu:addgrade' %}"
                                target="main">班级添加</a><img class="icon5" src="/static/img/coin21.png"/>
                        </dd>
                    {% endifequal %}
                {% endfor %}
                </dl>
                <dl class="system_log">
                {% for permission in user.role.r_p.all %}
                {% ifequal permission.p_en 'STUDENTLIS' %}
                    <dt>
                        <img class="icon1" src="/static/img/coin03.png"/><img class="icon2"
                                                                              src="/static/img/coin04.png"/>
                        学生管理<img class="icon3"
                                 src="/static/img/coin19.png"/><img class="icon4"
                                                                    src="/static/img/coin20.png"/>
                    </dt>
                    <dd>
                        <img class="coin11" src="/static/img/coin111.png"/><img class="coin22"
                                                                                src="/static/img/coin222.png"/><a
                            class="cks" href="{% url 'stu:student' %}"
                            target="main">学生列表</a><img class="icon5" src="/static/img/coin21.png"/>
                    </dd>
                {% endifequal %}
            {% endfor %}
            {% for permission in user.role.r_p.all %}
                {% ifequal permission.p_en 'STUDENTADD' %}
                    <dd>
                        <img class="coin11" src="/static/img/coin111.png"/><img class="coin22"
                                                                                src="/static/img/coin222.png"/><a
                            class="cks" href="{% url 'stu:addstu' %}?id=0"
                            target="main">添加学生</a><img class="icon5" src="/static/img/coin21.png"/>
                    </dd>
                {% endifequal %}
            {% endfor %}
            </dl>
            <dl class="system_log">
                <dt>
                    <img class="icon1" src="/static/img/coinL1.png"/><img class="icon2"
                                                                          src="/static/img/coinL2.png"/> 系统管理<img
                        class="icon3"
                        src="/static/img/coin19.png"/><img class="icon4"
                                                           src="/static/img/coin20.png"/>
                </dt>
                <dd>
                    <img class="coin11" src="/static/img/coin111.png"/><img class="coin22"
                                                                            src="/static/img/coin222.png"/><a
                        href="changepwd.html"
                        target="main" class="cks">修改密码</a><img class="icon5"
                                                               src="/static/img/coin21.png"/>
                </dd>
                <dd>
                    <img class="coin11" src="/static/img/coin111.png"/><img class="coin22"
                                                                            src="/static/img/coin222.png"/><a
                        class="cks">退出</a><img
                        class="icon5" src="/static/img/coin21.png"/>
                </dd>
            </dl>
        </div>

    </div>
{% endblock %}

stu_ms/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>登录</title>
<link rel="stylesheet" type="text/css" href="css/public.css" />
<link rel="stylesheet" type="text/css" href="css/page.css" />
<script type="text/javascript" src="js/jquery.min.js"></script>
<script type="text/javascript" src="js/public.js"></script>
</head>
<body>

	<!-- 登录body -->
	<div class="logDiv">
		<img class="logBanner" src="img/logBanner.png" />
		<div class="logGet">
			<!-- 头部提示信息 -->
			<div class="logD logDtip">
				<p class="p1">登录</p>
			</div>
			<!-- 输入框 -->
			<div class="lgD">
				<img class="img1" src="img/logName.png" /><input type="text"
					placeholder="输入用户名" />
			</div>
			<div class="lgD">
				<img class="img1" src="img/logPwd.png" /><input type="text"
					placeholder="输入用户密码" />
			</div>
			<div class="logC">
				<a href="index.html" target="_self"><button>登 录</button></a>
			</div>
		</div>
	</div>
	<!-- 登录body  end -->

	<!-- 登录页面底部 -->
	<div class="logFoot">
		<p class="p1">版权所有：安徽公司公司</p>
		<p class="p2">123456789</p>
	</div>
	<!-- 登录页面底部end -->
   
</body>
</html>

stu_ms/templates/student.html
{% extends 'base.html' %}
{% block title %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="generator" content=""/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
{% endblock %}
{% block extCSS %}
<link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print"/>
{#    <link href="/static/css/print.css" rel="stylesheet" type="text/css" media="print"/>#}
{% endblock %}
    {% block extJS %}
        <script src="/static/js/jquery-1.10.1.min.js"></script>
    <script src="/static/js/side.js" type="text/javascript"></script>

    <!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
        <script type="text/javascript">
        function delstu(i) {
            csrf = $('[name="csrfmiddlewaretoken"]').val();
            $.ajax({
                url:'/stu/api/student/' + i + '/',
                type:'DELETE',
                dataType: 'json',
                headers: {'X-CSRFToken':csrf},
                success:function (data) {
                    alert('删除成功');
                    location.href = '/stu/student/'
                },
                error:function (data) {
                    alert('删除失败')
                }
            });
        }
        
        $(function () {
            $.get('/stu/api/student/', function (msg) {
                var tr_html = '';
                var msg = msg['data']['results'];
                for (var i=0; i< msg.length; i++){
                    {#alert(msg[i]);#}
                    tr_html += '<tr>';
                    tr_html += '<td>' + msg[i]['id'] + '</td>';
                    tr_html += '<td>' + msg[i].s_name + '</td>';
                    tr_html += '<td>' + msg[i].g_name + '</td>';
                    tr_html += '<td><img src="' + msg[i].s_img + '" style="width: 30px;height: 30px"></td>';
                    tr_html += '<td><a href="{% url 'stu:editstu' %}?id=' + msg[i]['id'] + '">编辑</a> |';
                    tr_html += '<a href="javascrip:void(0)" onclick="delstu(' + msg[i]['id'] + ');">删除</a></td>';
                    tr_html += '</tr>';
                }
                $('#stu').append(tr_html);
            }, 'json');
        })
        </script>
    {% endblock %}
{% block content %}
<!-- MainForm -->
<div id="MainForm">
    <div class="form_boxA">
        <h2>学生信息列表</h2>
    {% csrf_token %}
        <table cellpadding="0" cellspacing="0" id="stu">
            <tr>
                <th>序号</th>
                <th>学生名称</th>
                <th>班级</th>
                <th>头像</th>
                <th>操作</th>
            </tr>
{#            {% for stu in pages %}#}
{#                <tr>#}
{#                    <td>{{ stu.id }}</td>#}
{#                    <td>{{ stu.s_name }}</td>#}
{#                    <td>{{ stu.g.g_name }}</td>#}
{#                    <td><img src="/media/{{ stu.s_img }}" style="width: 30px;height: 30px"></td>#}
{#                    <td>#}
{#                        <a href="{% url 'stu:editstu' %}?id={{ stu.id }}">编辑</a> |#}
{#                        <a href="{% url 'stu:delstu' %}?id={{ stu.id }}">删除</a>#}
{#                        <a href="javascrip:void(0)" onclick="delstu({{ stu.id }});">删除</a>#}
{#                    </td>#}
{#                </tr>#}
{#            {% endfor %}#}
        </table>
        <p class="msg">共找到47条年度预算记录，当前显示从第1条至第10条</p>
    </div>

    <ul id="PageNum">
        <li><a href="{% url 'stu:student' %}">首页</a></li>
        {% if pages.has_previous %}
            <li><a href="{% url 'stu:student' %}?page_num={{ pages.previous_page_number }}">上一页</a></li>
        {% endif %}
        {% for i in pages.paginator.page_range %}
            {% ifequal pages.number i  %}
            <li page_num="{{ i }}"><a href="{% url 'stu:student' %}?page_num={{ i }}" class="active">{{ i }}</a></li>
            {% else %}
            <li page_num="{{ i }}"><a href="{% url 'stu:student' %}?page_num={{ i }}">{{ i }}</a></li>
            {% endifequal %}
        {% endfor %}
        {% if pages.has_next %}
            <li><a href="{% url 'stu:student' %}?page_num={{ pages.next_page_number }}">下一页</a></li>
        {% endif %}
        <li><a href="{% url 'stu:student' %}?page_num={{ pages.paginator.num_pages }}">尾页</a></li>
    </ul>

</div>
{% endblock %}

stu_ms/templates/student_bak.html
{% extends 'base.html' %}
{% block title %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="generator" content=""/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
{% endblock %}
{% block extCSS %}
<link href="/static/css/haiersoft.css" rel="stylesheet" type="text/css" media="screen,print"/>
{#    <link href="/static/css/print.css" rel="stylesheet" type="text/css" media="print"/>#}
{% endblock %}
    {% block extJS %}
        <script src="/static/js/jquery-1.10.1.min.js"></script>
    <script src="/static/js/side.js" type="text/javascript"></script>

    <!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<![endif]-->
        <script type="text/javascript">
        function delstu(i) {
            csrf = $('[name="csrfmiddlewaretoken"]').val();
            $.ajax({
                url:'/stu/api/student/' + i + '/',
                type:'DELETE',
                dataType: 'json',
                headers: {'X-CSRFToken':csrf},
                success:function (data) {
                    alert('删除成功');
                    location.href = '/stu/student/'
                },
                error:function (data) {
                    alert('删除失败')
                }
            });
        }
        
        $(function () {
            $.get('/stu/api/student/', function (msg) {
                console.log(msg)
            }, 'json');
        })
        </script>
    {% endblock %}
{% block content %}
<!-- MainForm -->
<div id="MainForm">
    <div class="form_boxA">
        <h2>学生信息列表</h2>
    {% csrf_token %}
        <table cellpadding="0" cellspacing="0">
            <tr>
                <th>序号</th>
                <th>学生名称</th>
                <th>班级</th>
                <th>头像</th>
                <th>操作</th>
            </tr>
            {% for stu in pages %}
                <tr>
                    <td>{{ stu.id }}</td>
                    <td>{{ stu.s_name }}</td>
                    <td>{{ stu.g.g_name }}</td>
                    <td><img src="/media/{{ stu.s_img }}" style="width: 30px;height: 30px"></td>
                    <td>
                        <a href="{% url 'stu:editstu' %}?id={{ stu.id }}">编辑</a> |
{#                        <a href="{% url 'stu:delstu' %}?id={{ stu.id }}">删除</a>#}
                        <a href="javascrip:void(0)" onclick="delstu({{ stu.id }});">删除</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <p class="msg">共找到47条年度预算记录，当前显示从第1条至第10条</p>
    </div>

    <ul id="PageNum">
        <li><a href="{% url 'stu:student' %}">首页</a></li>
        {% if pages.has_previous %}
            <li><a href="{% url 'stu:student' %}?page_num={{ pages.previous_page_number }}">上一页</a></li>
        {% endif %}
        {% for i in pages.paginator.page_range %}
            {% ifequal pages.number i  %}
            <li page_num="{{ i }}"><a href="{% url 'stu:student' %}?page_num={{ i }}" class="active">{{ i }}</a></li>
            {% else %}
            <li page_num="{{ i }}"><a href="{% url 'stu:student' %}?page_num={{ i }}">{{ i }}</a></li>
            {% endifequal %}
        {% endfor %}
        {% if pages.has_next %}
            <li><a href="{% url 'stu:student' %}?page_num={{ pages.next_page_number }}">下一页</a></li>
        {% endif %}
        <li><a href="{% url 'stu:student' %}?page_num={{ pages.paginator.num_pages }}">尾页</a></li>
    </ul>

</div>
{% endblock %}