shop_market/shop_market/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from shop_market.settings import MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^xf/', include('xfmart.urls', namespace='xf')),
    url(r'^user/', include('user.urls', namespace='user')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

shop_market/user/urls.py
from django.conf.urls import url

from user import views


urlpatterns = [
    # 注册
    url(r'^register/', views.register, name='register'),
    # 检查用户名是否存在
    url(r'^checkuser', views.check_user, name='checkuser'),
    # 登录
    url(r'^login/', views.login, name='login'),
    # 登出
    url(r'^logout/', views.logout, name='logout'),
]

shop_market/templates/mine/mine.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/mine/mine.css' %}">
{% endblock %}

{% block EXTJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'app/mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="mine">

        <div class="fixed">
            <!--如果登录，展示头像-->
            {% if user %}
                <img src="/media/{{ user.icon }}" alt="icon">
                <!--或者-->
            {% else %}
                <span class="glyphicon glyphicon-user"></span>
            {% endif %}
            <!--判断结束-->

            <!--如果登录，展示姓名-->
            {% if user %}
                <p>{{ user.username }}</p>
                <!--或者展示登录的链接-->
            {% else %}
                <a href="{% url 'user:login' %}">登录</a>
            {% endif %}
            <!--判断结束-->


            <p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>
            <!--如果没有登录,展示注册信息-->
            {% if not user %}
                <div id="regis">
                    <a href="{% url 'user:register' %}">注册</a>
                </div>
            {% endif %}
            <!--判断结束-->

            <p><span class="glyphicon glyphicon-heart"></span><span>收藏</span></p>

        </div>

        <div class="mine">

            <p>我的订单<a href="#">更多&gt;</a></p>

            <div id="nav">

                <ul>
                    <li>
                        <dl>
                            <dt><span id="wait_pay_list" class="glyphicon glyphicon-usd"></span>
                                <span class="badge">
                                    <!--代付款的数量-->
                                    {{ wait_pay }}
                                </span></dt>
                            <dd>待付款</dd>
                        </dl>

                    </li>
                    <li>
                        <dl>
                            <dt><span id="order_payed_list" class="glyphicon glyphicon-envelope"></span>
                                {% if payed %}
                                    <span class="badge">
                                    <!--待收货的数量-->
                                    {{ payed }}
                                </span></dt>
                                {% endif %}
                            <dd>待收货</dd>
                        </dl>

                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-pencil"></span></dt>
                            <dd>待评价</dd>
                        </dl>

                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-retweet"></span></dt>
                            <dd>退款/售后</dd>
                        </dl>

                    </li>

                </ul>

            </div>

            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                            <span>积分商城</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                            <span>优惠券</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-import"></span></dt>
                            <span>收货地址</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                            <span>客户反馈</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-certificate"></span></dt>
                            <span>关于我们</span>
                        </dl>
                    </li>
                </ul>
            </menu>

            <!--如果登录了,则退出展示-->
            {% if user %}
                <p class="logout">
                    <a href="{% url 'user:logout' %}">退出</a>
                </p>
            {% endif %}
            <!--判断结束-->
        </div>
    </div>


{% endblock %}