shop_market/shop_market/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from shop_market.settings import MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^xf/', include('xfmart.urls', namespace='xf')),
    url(r'^user/', include('user.urls', namespace='user')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

shop_market/user/urls.py
from django.conf.urls import url

from user import views


urlpatterns = [
    # 注册
    url(r'^register/', views.register, name='register'),
    # 检查用户名是否存在
    url(r'^checkuser', views.check_user, name='checkuser'),
    # 登录
    url(r'^login/', views.login, name='login'),
    # 登出
    url(r'^logout/', views.logout, name='logout'),
]

shop_market/xfmart/urls.py
from django.conf.urls import url

from xfmart import views

urlpatterns = [
    # 首页
    url(r'^home/', views.index, name='home'),
    # 闪购页面
    url(r'^market/$', views.market, name='market'),
    url(r'^market/(\d+)/(\d+)/(\d+)/', views.user_market, name='market_param'),
    # 购物车
    url(r'^cart/', views.cart, name='cart'),
    # 我的页面
    url(r'^mine/', views.mine, name='mine'),

    # 添加购物车商品
    url(r'^addCart/', views.add_cart, name='addCart'),
    # 删除购物车商品
    url(r'^subCart/', views.sub_cart, name='subCart'),
    # 改变购物车商品状态
    url(r'^changeCartStatus/', views.change_cart_status, name='changeCartStatus'),
    # 下单
    url(r'^generateOrder/', views.generate_order, name='generateOrder'),
    # 修改订单状态（支付）
    url(r'^changeOrderStatus/', views.change_order_status, name='changeOrderStatus'),
    # 待支付页面
    url(r'^waitPay/', views.wait_pay, name='waitPay'),
    # 待收货页面
    url(r'^orderPayed/', views.order_payed, name='orderPayed'),
    # 待支付跳转到支付页面
    url(r'^waitPaytoPay', views.wait_pay_to_pay, name='waitPaytoPay')
]

shop_market/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    {% block extCSS %}

    {% endblock %}
    <title>{{ title }}</title>
</head>
<body>

{% block header %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}

<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
{% block EXTJS %}

{% endblock %}
</body>
</html>

shop_market/templates/base_main.html
{% extends 'base.html' %}
{% load static %}
{% block extCSS %}

    <link rel="stylesheet" href="{% static 'css/base.css' %}">

{% endblock %}

{% block header %}

    <header></header>

{% endblock %}

{% block footer %}

    <footer>

        <a href="{% url 'xf:home' %}" class="home">

            <dl>

                <dt>
                    <span></span>
                </dt>
                <dd>首页</dd>

            </dl>

        </a>
        <a href="{% url 'xf:market' %}" class="market">

            <dl>

                <dt>
                    <span></span>
                </dt>
                <dd>闪购</dd>

            </dl>

        </a>
        <a href="{% url 'xf:cart' %}" class="cart">

            <dl>

                <dt>
                    <span></span>
                </dt>
                <dd>购物车</dd>

            </dl>

        </a>
        <a href="{% url 'xf:mine' %}" class="mine">

            <dl>

                <dt>
                    <span></span>
                </dt>
                <dd>我的</dd>

            </dl>

        </a>

    </footer>

{% endblock %}